version: 3

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  iaac:
    taskfile: ./iaac/Taskfile.yml
    dir: ./iaac

tasks:
  pretty:
    aliases: [p, format, fmt]
    desc: Uses the Prettier CLI tool to format the codebase.
    cmds: ['prettier --write .']

  build:eks:
    desc: Uses Terraform to build the EKS cluster where the API is to be deployed.
    cmds: ['task iaac:build']

  build:api:
    desc: Build the API into a Docker Image.
    cmds: ['task api:build']

  start:api:
    desc: Starts the API as a Docker Container.
    deps: [api:build]
    cmds: ['task api:start']

  stop:api:
    desc: Stops the API Docker Container.
    cmds: ['task api:stop']

  destroy:eks:
    desc: Destroys the EKS cluster w/ Terraform.
    cmds: ['task iaac:destroy']

  start:fresh:
    desc: Performs all of the steps necessary to build and start the app in its own EKS cluster.
    cmds:
      - task iaac:build
      - task api:build
      - task api:start
