version: 3

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  iaac:
    taskfile: ./iaac/Taskfile.yml
    dir: ./iaac

tasks:
  pretty:
    aliases: [p, format, fmt]
    desc: Uses the Prettier CLI tool to format the codebase.
    cmds: ['prettier --write .']

  build:eks:
    desc: Uses Terraform to build the EKS cluster where the API is to be deployed.
    cmds: ['task iaac:build']

  build:api:
    desc: Build the API into a Docker Image.
    cmds: ['task api:build']

  start:api:
    desc: Starts the API as a Docker Container.
    cmds: ['task api:start']

  stop:api:
    desc: Stops the API Docker Container.
    cmds: ['task api:stop']

  logs:api:
    cmds: ['docker logs liatrio-api']

  test:api:
    cmds: ['bash ./tests/api.sh']

  test:cluster:
    cmds: ['bash ./tests/cluster.sh']

  test:all:
    cmds:
      - task test:api
      - task test:cluster

  destroy:eks:
    desc: Destroys the EKS cluster w/ Terraform.
    cmds: ['task iaac:destroy']

  fresh:
    aliases: ['fresh']
    desc: Performs all of the steps necessary to build and start the app in its own EKS cluster.
    silent: true
    cmds:
      # Builds the EKS cluster and Docker image in parallel.
      - task --parallel iaac:build api:build
      # Starts the API docker image.
      - task start:api
      - task test:all
