#region Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: liatrio
#endregion Namespace
---
#region ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: 'liatrio'
  name: 'liatrio-api-configmap'
data:
  API_PREFIX: '/api/v1'
  APP_NAME: 'liatrio-api'
  APP_VERSION: '1.0.0'
  APP_PORT: '8080'
#endregion ConfigMap
---
#region Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-api
  namespace: liatrio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liatrio-api
  template:
    metadata:
      labels:
        app: liatrio-api
    spec:
      containers:
        - name: liatrio-api
          image: 4lch4/liatrio-api:latest
          resources:
            limits:
              cpu: '600m'
              memory: '750Mi'
            requests:
              cpu: '200m'
              memory: '250Mi'
          envFrom:
            - configMapRef:
                name: 'liatrio-api-configmap'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: '/api/v1/health/liveness'
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: '/api/v1/health/readiness'
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 10
#endregion Deployment
---
#region Service
kind: Service
apiVersion: v1
metadata:
  name: 'liatrio-api'
  namespace: 'liatrio'
  labels:
    app: 'liatrio-api'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: web
  selector:
    app: 'liatrio-api'
#endregion Service
---
#region Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: liatrio-api
  namespace: liatrio
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: liatrio-api
                port:
                  number: 8080
#endregion Ingress

